# Usar a imagem oficial do Node.js como base
FROM node:latest

# Definir diretório de trabalho
WORKDIR /app

# Copiar o pacote JSON e bloquear arquivos
COPY appDeNotas/package*.json ./

# Instalar dependências do projeto
RUN npm install

# Copiar todos os arquivos do projeto para o container
COPY appDeNotas/ .

# Expor a porta que sua aplicação usa
EXPOSE 3000

# Comando para iniciar a aplicação via PM2
CMD ["node", "./node_modules/pm2/bin/pm2-runtime", "start", "npm", "--", "start"]
